// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/AutoDrive.h"
#include "Commands/AutoPincers.h"
#include "Commands/Autonomous.h"
#include "Commands/DriveWithJoystick.h"
#include "Commands/FLManual.h"
#include "Commands/FLToggleDown.h"
#include "Commands/FLToggleUp.h"
#include "Commands/GetFLEncoder.h"
#include "Commands/GetSLEncoder.h"
#include "Commands/MovePincersWithJoystick.h"
#include "Commands/SLCatch.h"
#include "Commands/SLClose.h"
#include "Commands/SLManualDown.h"
#include "Commands/SLManualUp.h"

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI() {
	// Process operator interface input here.
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

	xboxstick = new Joystick(1);
	
	start = new JoystickButton(xboxstick, 8);
	start->WhenPressed(new GetFLEncoder());
	back = new JoystickButton(xboxstick, 7);
	back->WhenPressed(new GetSLEncoder());
	rightBumper = new JoystickButton(xboxstick, 6);
	rightBumper->WhileHeld(new SLManualUp());
	leftBumper = new JoystickButton(xboxstick, 5);
	leftBumper->WhileHeld(new SLManualDown());
	y = new JoystickButton(xboxstick, 4);
	y->WhenPressed(new FLToggleUp());
	x = new JoystickButton(xboxstick, 3);
	x->WhenPressed(new FLToggleDown());
	b = new JoystickButton(xboxstick, 2);
	b->WhenPressed(new SLClose());
	a = new JoystickButton(xboxstick, 1);
	a->WhenPressed(new SLCatch());
     

        // SmartDashboard Buttons
	SmartDashboard::PutData("DriveWithJoystick", new DriveWithJoystick());

	SmartDashboard::PutData("FLManual", new FLManual());

	SmartDashboard::PutData("FLToggleUp", new FLToggleUp());

	SmartDashboard::PutData("FLToggleDown", new FLToggleDown());

	SmartDashboard::PutData("SLManual Up", new SLManualUp());

	SmartDashboard::PutData("SLManualDown", new SLManualDown());

	SmartDashboard::PutData("SLClose", new SLClose());

	SmartDashboard::PutData("SLCatch", new SLCatch());

	SmartDashboard::PutData("MovePincersWithJoystick", new MovePincersWithJoystick());

	SmartDashboard::PutData("GetSLEncoder", new GetSLEncoder());

	SmartDashboard::PutData("GetFLEncoder", new GetFLEncoder());

	SmartDashboard::PutData("AutoPincers", new AutoPincers());

	SmartDashboard::PutData("Autonomous", new Autonomous());

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

Joystick* OI::getxboxstick() {
	return xboxstick;
}

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
